# Generated by Django 2.2.3 on 2019-07-26 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_industry', '0004_auto_20190726_0821'),
        ('organization', '0005_auto_20190726_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('name_slug', models.CharField(editable=False, max_length=256, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('client_industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_industry.ClientIndustry')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
