# compose file for production environment
# docker-compose -f docker-compose-dev.yml build   and then
# docker-compose -f docker-compose-prod.yml up

version: '3'
    
services:
  
  # db service
  db:
    image: postgres:10.7
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - DATABASE_URL: postgresql://....
    restart: on-failure
    expose:
      - "5432"

  # app service
  web:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  dbdata: