# Generated by Django 2.2.3 on 2019-07-24 21:09

import common.enums
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('name_slug', models.CharField(blank=True, max_length=256, unique=True)),
                ('status', models.CharField(choices=[(common.enums.Status('active'), 'active'), (common.enums.Status('disabled'), 'disabled'), (common.enums.Status('archived'), 'archived')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
