# Generated by Django 2.2.3 on 2019-07-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190724_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('archived', 'archived')], max_length=10),
        ),
    ]
