# Generated by Django 2.2.3 on 2019-07-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190725_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name_slug',
            field=models.CharField(editable=False, max_length=256, unique=True),
        ),
    ]
