# Generated by Django 2.2.3 on 2019-07-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='completion_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
