# Generated by Django 2.2.13 on 2020-07-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('task_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engagement.Engagement'),
        ),
    ]
