# Generated by Django 2.2.5 on 2019-10-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20190726_1935'),
        ('task_assignment', '0002_auto_20190730_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization'),
        ),
    ]
