# Generated by Django 2.2.5 on 2019-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignment', '0003_taskassignment_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
