# Generated by Django 2.2.5 on 2019-10-09 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignment', '0004_auto_20191009_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='completion_date_time',
            new_name='end_date_time',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('running', 'running'), ('in review', 'in review'), ('reviewed', 'reviewed'), ('closed', 'closed')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
