# Generated by Django 2.2.5 on 2019-10-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_position', '0002_jobposition_src_job_position_id'),
        ('employee', '0002_employee_is_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_position.JobPosition'),
        ),
    ]
