# Generated by Django 2.2.5 on 2019-10-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20191004_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_terminated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
