# Generated by Django 2.2.5 on 2019-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_date_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='src_resource_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
