# Generated by Django 2.2.5 on 2019-10-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_src_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='file_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
