# Generated by Django 3.0.8 on 2020-07-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20200604_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('archived', 'archived'), ('deleted', 'deleted')], max_length=10),
        ),
    ]
