# Generated by Django 2.2.13 on 2020-07-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_industry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientindustry',
            name='name_slug',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
