# Generated by Django 2.2.3 on 2019-07-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_industry', '0002_auto_20190726_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientindustry',
            options={'verbose_name_plural': 'client industries'},
        ),
    ]
