# Generated by Django 2.2.3 on 2019-07-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_industry', '0003_auto_20190726_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientindustry',
            options={'verbose_name_plural': 'Client Industries'},
        ),
    ]
