# Generated by Django 2.2.5 on 2019-09-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20190726_1935'),
        ('client_industry', '0004_auto_20190726_0821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientindustry',
            unique_together={('name', 'name_slug', 'organization')},
        ),
    ]
