# Generated by Django 2.2.5 on 2019-09-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_industry', '0005_auto_20190925_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientindustry',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientindustry',
            name='name_slug',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
