# Generated by Django 2.2.5 on 2019-10-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineofservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineofservice',
            name='src_los_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
