# kubectl apply -f k8s/service-account.yml
# TOKEN=$(kubectl get secret $(kubectl get secret | grep cicd-token | awk '{print $1}') -o jsonpath='{.data.token}' | base64 --decode)

# creating a Service Account, which is basically a user on your cluster

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd
  namespace: resourceideaapi
