# Generated by Django 2.2.3 on 2019-07-30 12:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('organization', '0005_auto_20190726_1935'),
        ('employee', '0002_employee_is_resource'),
        ('lineofservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('planned_start_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('not started', 'not started'), ('running', 'running'), ('in review', 'in review'), ('reviewed', 'reviewed'), ('closed', 'closed')], max_length=10)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_engagements', to='client.Client')),
                ('line_of_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineofservice.LineOfService')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Employee')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_engagements', to='employee.Employee')),
            ],
            options={
                'db_table': 'engagement',
            },
        ),
    ]
