# Generated by Django 2.2.3 on 2019-07-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_engagements', to='client.Client'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='line_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineofservice.LineOfService'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_engagements', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
