# Generated by Django 2.2.3 on 2019-07-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_auto_20190730_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('running', 'running'), ('in review', 'in review'), ('reviewed', 'reviewed'), ('closed', 'closed')], max_length=20),
        ),
    ]
