# Generated by Django 2.2.5 on 2019-10-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_auto_20190730_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='src_project_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
