# Generated by Django 2.2.12 on 2020-06-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_position', '0002_jobposition_src_job_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
