# Generated by Django 2.2.5 on 2019-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='src_job_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
