# Generated by Django 2.2.5 on 2019-10-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_src_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
