# Generated by Django 2.2.5 on 2019-10-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20191008_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date_time',
        ),
    ]
